<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_info_layer"
 *
 * Auto generated by Extension Builder 2014-12-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'RKW Info Layer',
	'description' => 'Info Layer Plugin for RKW',
	'category' => 'plugin',
	'author' => 'Jeffrey Nellissen, Steffen Kroggel',
	'author_email' => 'nellissen@bergisch-media.de, developer@steffenkroggel.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '8.7.0',
	'constraints' => [
		'depends' => [
            'typo3' => '7.6.0-7.6.99',
		],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
];